# Generated by Django 4.2.5 on 2023-11-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_description_alter_book_e_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
