# Generated by Django 4.2.5 on 2023-11-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
    ]
