# Generated by Django 4.2.5 on 2023-11-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_authors_alter_book_author_delete_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='books',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='authors',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='authors',
            name='lastname',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='author', to='bookstore.authors'),
        ),
    ]
