# Generated by Django 4.2.5 on 2023-11-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_rename_name_authors_firstname_remove_authors_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='lastname',
        ),
    ]
