# Generated by Django 4.2.5 on 2023-11-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='categorys', to='bookstore.category'),
        ),
        migrations.DeleteModel(
            name='Category_book',
        ),
    ]
