# Generated by Django 4.2.5 on 2023-11-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_book_category_delete_category_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='bookstore.category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('New', 'New'), ('In Progress', 'In Progress'), ('cancelled', 'cancelled')], default='New', max_length=100),
        ),
    ]
