# Generated by Django 4.2.5 on 2023-11-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_alter_authors_description_alter_book_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
    ]
