# Generated by Django 4.2.5 on 2023-11-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_rename_user_id_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='description',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
