# Generated by Django 4.2.5 on 2023-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0015_alter_authors_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
