# Generated by Django 4.2.5 on 2023-11-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0017_alter_authors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
