# Generated by Django 4.2.5 on 2023-11-18 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0024_alter_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
