# Generated by Django 4.2.5 on 2023-11-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0027_remove_order_customer_id_order_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
