# Generated by Django 4.2.5 on 2023-11-18 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0028_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01, message='Price must be greater than or equal to 0.01.'), django.core.validators.MaxValueValidator(9999.99, message='Price must be less than or equal to 9999.99.')]),
        ),
    ]
