# Generated by Django 4.2.5 on 2023-11-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0032_alter_book_e_version_alter_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('ONTA NEGR BOLASI', 'DETECTIVE_BOOK'), ('QALB KITOBI', 'ISLAMIC_BOOK'), ('DEVONA', 'CRIMINAL_BOOK'), ('BOY OTA KAMBAGAL OTA', 'MOTIVATIONAL')], max_length=100),
        ),
    ]
