# Generated by Django 4.2.5 on 2023-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0034_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('done', 'done'), ('new', 'new'), ('in_progress', 'in_progress'), ('cancelled', 'cancelled')], default='new', max_length=100),
        ),
    ]
